version: '3.9'
services:

  appointment-service-db:
    image: mysql:8.0.23
    platform: linux/amd64
    container_name: appointment-service-db
    volumes:
      - appointment-service-db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'appointment'
      MYSQL_PASSWORD: 'appointment'
      MYSQL_DATABASE: 'appointment_data'
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET collation_connection = utf8_unicode_ci;'
    ports:
      - "3306:3306"

volumes:
  appointment-service-db-data:
    driver: local