spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/appointment_data
    username: appointment
    password: appointment

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-durations-as-timestamps: false